### PR TITLE
Various text and bug fixes related to moving Sparks portal to learn.concord.org

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
@knowuh Sam is away so could you look at this PR?

**Comment by knowuh** [comment]
Looks good.  👍

**Comment by dougmartin** [comment]
Need to add https to concord.org url in about box.

**Comment by sfentress** [comment]
Hi @dougmartin I'm just looking at these recent changes before merging in Cynthia's recent work. Did this stuff go into static-standalone? I see one commit there, d67858249 "Merge in changes to master", but I don't actually understand what that is because it doesn't look like a merge, and it doesn't have the same changed files as this PR.

static-standalone had just branched off of master, so a merge into static-standalone should have been clean and straight-forward at that point. (If I try to merge now, I get a bunch of conflicts.)

**Comment by dougmartin** [comment]
When I did these changes I wasn't aware of the static-standalone branch so I made the changes off of master.  A couple of days later I learned of the static-standalone branch but I could not automatically merge the changes since there were files changed in folders in master (like  app) that didn't exist in static-standalone. so I manually applied the changes in master to static-standalone using a diff tool.

**Comment by sfentress** [comment]
I think that if you still do it as a merge, and fix the conflicts manually, it's better because then you can continue to track changes in master and easily merge them in (e.g. Cynthia's edits), without having every future change need to be manually copied over.

I can try and rebase the static-standalone branch such that we can continue to merge in changes.

**Pull request merged**
